FROM php:5.6.29-apache

RUN apt-get update && apt-get install -y zlib1g-dev libmemcached-dev \
    && pecl install memcached \
    && docker-php-ext-enable memcached \
    && rm -rf /var/lib/apt/lists

VOLUME /var/www/html

COPY src/ /var/www/html/
COPY php-memcached-opt.ini /usr/local/etc/php/conf.d/docker-php-ext-memcached.ini
